"""add tenant is_internal and user is_internal_tester

Revision ID: 08876c4b3cb5
Revises: 34a9d21f4d94
Create Date: 2026-07-17 06:07:42.817039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08876c4b3cb5'
down_revision: Union[str, Sequence[str], None] = '34a9d21f4d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_internal_tester', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_internal_tester')
    op.drop_column('tenants', 'is_internal')
    # ### end Alembic commands ###
