"""add platform_announcements table

Revision ID: 1da6213afebf
Revises: d4e9f2a6c8b1
Create Date: 2026-07-15 11:01:57.450063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da6213afebf'
down_revision: Union[str, Sequence[str], None] = 'd4e9f2a6c8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_announcements_id'), 'platform_announcements', ['id'], unique=False)
    # ### end Alembic commands ###

    # Seed jedinstveni "beta" baner - ukljucen po defaultu jer je platforma
    # trenutno stvarno u beta fazi i besplatna.
    op.execute(
        """
        INSERT INTO platform_announcements (kind, message, is_active)
        VALUES (
            'beta',
            'Sattlio je trenutno u beta fazi — korištenje je potpuno besplatno. Kada krenemo sa naplatom, svi korisnici će biti blagovremeno obaviješteni.',
            true
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_announcements_id'), table_name='platform_announcements')
    op.drop_table('platform_announcements')
    # ### end Alembic commands ###
