"""add break times to special_days

Revision ID: 1ffb7f83fde8
Revises: b362ea6e6823
Create Date: 2026-07-10 14:39:59.896734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffb7f83fde8'
down_revision: Union[str, Sequence[str], None] = 'b362ea6e6823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_days', sa.Column('break_start', sa.Time(), nullable=True))
    op.add_column('special_days', sa.Column('break_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_days', 'break_end')
    op.drop_column('special_days', 'break_start')
    # ### end Alembic commands ###
