"""add system_settings and tenant is_beta_tester

Revision ID: 34a9d21f4d94
Revises: 1da6213afebf
Create Date: 2026-07-16 20:17:46.149010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a9d21f4d94'
down_revision: Union[str, Sequence[str], None] = '1da6213afebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.add_column('tenants', sa.Column('is_beta_tester', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Prekidac naplate startuje UGASEN - tokom besplatnog test perioda niko nije read-only.
    op.execute(
        "INSERT INTO system_settings (key, value) VALUES ('billing_enforcement_enabled', 'false')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_beta_tester')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
