"""add cancellation tracking fields to appointments

Revision ID: 367aad0baa6a
Revises: 800188bf5492
Create Date: 2026-07-10 07:47:55.720167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367aad0baa6a'
down_revision: Union[str, Sequence[str], None] = '800188bf5492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancelled_by_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by_name', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['cancelled_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'cancelled_at')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'cancelled_by_name')
    op.drop_column('appointments', 'cancelled_by_user_id')
    op.drop_column('appointments', 'cancelled_by_type')
    # ### end Alembic commands ###
