"""add jib and verification status to tenants

Revision ID: 51ef4ac5daef
Revises: 29a84f15ad0d
Create Date: 2026-06-29 13:11:28.963310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ef4ac5daef'
down_revision: Union[str, Sequence[str], None] = '29a84f15ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('jib', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('verification_status', sa.String(), nullable=False, server_default='pending'))
    op.create_index(op.f('ix_tenants_jib'), 'tenants', ['jib'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_jib'), table_name='tenants')
    op.drop_column('tenants', 'verification_status')
    op.drop_column('tenants', 'jib')
    # ### end Alembic commands ###
