"""add admin_action_logs table

Revision ID: 800188bf5492
Revises: bf85409003b6
Create Date: 2026-07-07 11:30:10.550860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800188bf5492'
down_revision: Union[str, Sequence[str], None] = 'bf85409003b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_admin_user_id'), 'admin_action_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_id'), 'admin_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target_id'), 'admin_action_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target_type'), 'admin_action_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_action_logs_target_type'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_target_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_admin_user_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
