"""add plan and trial_ends_at to tenants

Revision ID: a2ecdbcf310c
Revises: 78b3404cdf6d
Create Date: 2026-07-06 06:39:38.441320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ecdbcf310c'
down_revision: Union[str, Sequence[str], None] = '78b3404cdf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tenants', sa.Column('plan', sa.String(), nullable=False, server_default='trial'))
    op.add_column('tenants', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'plan')
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
