"""add_allow_self_booking_to_employee

Revision ID: b1c6584426a1
Revises: 53e4375d1284
Create Date: 2026-06-30 11:19:40.938925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c6584426a1'
down_revision: Union[str, Sequence[str], None] = '53e4375d1284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('allow_self_booking', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'allow_self_booking')
    # ### end Alembic commands ###

