"""add can_manage_own_hours to employees

Revision ID: b362ea6e6823
Revises: 367aad0baa6a
Create Date: 2026-07-10 11:37:01.649079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b362ea6e6823'
down_revision: Union[str, Sequence[str], None] = '367aad0baa6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('can_manage_own_hours', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'can_manage_own_hours')
    # ### end Alembic commands ###
