"""add billing_status to tenants

Revision ID: bf85409003b6
Revises: e688902f338a
Create Date: 2026-07-07 10:13:15.834151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf85409003b6'
down_revision: Union[str, Sequence[str], None] = 'e688902f338a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('billing_status', sa.String(), nullable=False, server_default='trial'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'billing_status')
    # ### end Alembic commands ###

