"""add special days v2

Revision ID: e688902f338a
Revises: aa39d02f7188
Create Date: 2026-07-06 10:51:05.530200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e688902f338a'
down_revision: Union[str, Sequence[str], None] = 'aa39d02f7188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_days_employee_id'), 'special_days', ['employee_id'], unique=False)
    op.create_index(op.f('ix_special_days_id'), 'special_days', ['id'], unique=False)
    op.create_index(op.f('ix_special_days_tenant_id'), 'special_days', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_days_tenant_id'), table_name='special_days')
    op.drop_index(op.f('ix_special_days_id'), table_name='special_days')
    op.drop_index(op.f('ix_special_days_employee_id'), table_name='special_days')
    op.drop_table('special_days')
    # ### end Alembic commands ###
